-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgInjUQoXfEJVwUHpW
mozDiNNBz4NTaKl1ZZKNEIegzpygCgYIKoZIzj0DAQehRANCAARTUXIDIJFH0eQ3
lDfpwcLWXlkqurhbI7h8+1fd6OzrkPX3i9HZhJ2wOR5ejIxJhj/BigLZN1oglJpy
sTd1FSqN
-----END PRIVATE KEY-----